name: Security Audit

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 16 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: cargo generate-lockfile
      - run: cargo install cargo-audit
      - run: cargo audit --ignore RUSTSEC-2024-0436
